---
- hosts: xmpp.ipop-project.org
  remote_user: svpnuser
  sudo: yes
  tasks:
    - name: Install Python and friends
      apt: pkg={{ item }}
      with_items: [python, python-virtualenv, python-pip, tmux]
    - name: Install ejabberd
      apt: pkg=ejabberd
    - name: Configure ejabberd
      copy: >
        src=ejabberd.cfg
        dest=/etc/ejabberd/ejabberd.cfg
        mode=600
        owner=ejabberd
        group=ejabberd
      notify: Reload ejabberd
    - name: Install nginx
      apt: pkg=nginx
    - name: Configure nginx
      copy: >
        src=nginx.conf
        dest=/etc/nginx/conf.d/gvpn-webui.conf
        mode=644
        owner=root
        group=root
      notify: Reload nginx
    - name: Copy application files
      copy: src=../{{ item }} dest=/opt/groupvpn-webui/
      with_items:
      - defaults.json
      - django_project
      - groupvpn_webui
      - gvpn-config
      - manage.py
    - name: Copy setup.py
      copy: src=../setup.py dest=/opt/groupvpn-webui/
      notify:
      - Remove existing virtualenv
      - Initialize virtualenv
    - name: Create database
      command: env/bin/manage.py syncdb --noinput chdir=/opt/groupvpn-webui creates=db.sqlite3
    - name: Create static directory
      file: path=/opt/groupvpn-webui/static state=directory
    - name: Run django collectstatic
      command: env/bin/manage.py collectstatic --noinput chdir=/opt/groupvpn-webui
    - name: Kill django dev server in tmux if it's running
      shell: tmux kill-session -t groupvpn-webui-devserver || true
    - name: Start django dev server in tmux
      command: tmux new-session -d -s groupvpn-webui-devserver 'env/bin/manage.py runserver localhost:8080' chdir=/opt/groupvpn-webui
  handlers:
    - name: Reload ejabberd
      service: name=ejabberd enabled=yes state=reloaded
    - name: Reload nginx
      service: name=nginx enabled=yes state=reloaded
    - name: Remove existing virtualenv
      file: path=/opt/groupvpn-webui/env state=absent
    - name: Initialize virtualenv
      command: "{{ item }} chdir=/opt/groupvpn-webui"
      with_items:
      - virtualenv env
      - env/bin/pip install -e .
