---
- hosts: ptony82.dyndns-server.com
  remote_user: svpnuser
  sudo: yes
  tasks:
    - name: Install packages
      apt: pkg={{ item }}
      with_items:
      - ejabberd
      - python
      - python-virtualenv
      - python-pip
      - tmux
    - name: Configure ejabberd
      copy: >
        src=ejabberd.cfg
        dest=/etc/ejabberd/ejabberd.cfg
        mode=600
        owner=ejabberd
        group=ejabberd
      notify: Reload ejabberd
    - name: Copy application files
      copy: src={{ item }} dest=/opt/groupvpn-webui/
      with_items:
      - ../defaults.json
      - ../django_project
      - ../groupvpn_webui
      - ../gvpn-config
      - ../manage.py
      notify:
      - Run django syncdb
      - Kill django dev server in tmux if it's running
      - Start django dev server in tmux
    - name: Copy setup.py
      copy: src=../setup.py dest=/opt/groupvpn-webui/
      notify:
      - Remove existing virtualenv
      - Initialize virtualenv
  handlers:
    - name: Reload ejabberd
      service: name=ejabberd enabled=yes state=reloaded
    - name: Remove existing virtualenv
      file: path=/opt/groupvpn-webui/env state=absent
    - name: Initialize virtualenv
      command: "{{ item }} chdir=/opt/groupvpn-webui"
      with_items:
      - virtualenv env
      - env/bin/pip install -e .
    - name: Run django syncdb
      command: env/bin/manage.py syncdb --noinput chdir=/opt/groupvpn-webui
    - name: Kill django dev server in tmux if it's running
      shell: tmux kill-session -t groupvpn-webui-devserver || true
    - name: Start django dev server in tmux
      command: tmux new-session -d -s groupvpn-webui-devserver 'env/bin/manage.py runserver localhost:80' chdir=/opt/groupvpn-webui
